heladeria/urls.py
from django.urls import path
from . import views

app_name = 'heladeria'
urlpatterns = [
    path('', views.inicio, name='inicio'),
    path('about-us/', views.about_us, name='about_us'),
    path('recomendaciones/', views.recomendaciones, name='recomendaciones'),
]

lanievepag/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('heladeria.urls')),
    path('productos/', include('productos.urls')),
    path('login/', include('login.urls')),
] 

login/urls.py
from django.urls import path
from . import views

app_name = 'usuarios'
urlpatterns = [
    path('login/', views.login1, name='login1'),
]

productos/urls.py
from django.urls import path
from . import views

app_name = 'productos'
urlpatterns = [
    path('catalogo/', views.catalogo, name='catalogo'),
]

heladeria/models.py
from django.db import models

# Create your models here.

login/models.py
from django.db import models

# Create your models here.

productos/models.py
from django.db import models

# Create your models here.

heladeria/views.py
from django.shortcuts import render

# Create your views here.
def inicio(request):
    return render(request, 'heladeria/inicio.html')


def about_us(request):
    return render(request, 'heladeria/about_us.html')

def recomendaciones(request):
    return render(request, 'heladeria/recomendaciones.html')

login/views.py
from django.shortcuts import render

# Create your views here.
def login1(request):
    return render(request, 'login/usuarios.html')

productos/views.py
from django.shortcuts import render

# Create your views here.
def catalogo(request):
    return render(request, 'productos/catalogo.html')

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
  {% load static %}
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>{% block tittle %} HELADERÍA LA NIEVE {% endblock %}</title>
  <link rel="stylesheet" href="/static/css/stylebase.css">
  <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
</head>
<body>
  <header class="header">
    <div class="logo">
      <img src="/static/images/logo.png" alt="Logo de la marca">
    </div>
    <nav>
      <ul class="nav-links">
        <li><a href="{% url 'login:login1' %}">Iniciar Sesión</a></li>
        <li><a href="{% url 'productos:catalogo' %}">Productos</a></li>
        <li><a href="{% url 'heladeria:about_us' %}">About Us</a></li>
        <li><a href="{% url 'heladeria:recomendaciones' %}">Recomendaciones</a></li>
      </ul>
    </nav>
    <a href="#" class="btn"><button>Descarga nuestra app!</button></a>
  </header>

  {% block content %}
  {% endblock %}

</body>
</html>